spring.application.name=intelli_folio

# mysql database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# flyway migration
spring.flyway.enabled=true

# mybatis sql mapper
mybatis.configuration.map-underscore-to-camel-case=true

# qdrant config
qdrant.host=http://localhost:6333
qdrant.collection=portfolio_chunks
qdrant.vector-size=1024

# ollama embedding server config
embedding.base-url=http://127.0.0.1:11434
embedding.model=jeffh/intfloat-multilingual-e5-large-instruct:q8_0
embedding.timeout-ms=5000

